sic5-ainger-master/sic5-ainger-master/app/models.py
from . import db
from datetime import datetime

class Student(db.Model):
    __tablename__ = 'students'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    class_name = db.Column(db.String(64), nullable=False)
    address = db.Column(db.String(128), nullable=False)
    fingerprint = db.Column(db.String(64), nullable=False)
    

    loans = db.relationship('Loan', backref='student', lazy=True, cascade='all, delete-orphan')

class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256), nullable=True)
    ISBN = db.Column(db.String(256), nullable=False)
    author = db.Column(db.String(256), nullable=True)
    year = db.Column(db.String(256), nullable=True)
    publisher = db.Column(db.String(256), nullable=True)
    image_url = db.Column(db.String(256), nullable=True)
    loans = db.relationship('Loan', backref='book', lazy=True, cascade='all, delete-orphan')

class Loan(db.Model):
    __tablename__ = 'loans'
    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey('students.id'), nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey('books.id'), nullable=False)
    loan_date = db.Column(db.Date, nullable=False, default=datetime.utcnow)
    return_date = db.Column(db.Date, nullable=False)
    is_return = db.Column(db.Boolean, nullable=True, default=False)

sic5-ainger-master/sic5-ainger-master/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from .config import Config
from flask_wtf.csrf import CSRFProtect

db = SQLAlchemy()
migrate = Migrate()
csrf = CSRFProtect()
def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    
    db.init_app(app)
    migrate.init_app(app, db)
    csrf.init_app(app)
    
    from .models import Student, Book, Loan
    from .routes import main
    app.register_blueprint(main)
    
    return app

sic5-ainger-master/sic5-ainger-master/app/routes.py
from . import create_app, db
from .models import Student, Book, Loan
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_wtf.csrf import CSRFProtect
import pickle
import pandas
from datetime import datetime
import numpy as np

pbr_df = pickle.load(open('PopularBookRecommendation.pkl','rb'))
pt = pickle.load(open('pt.pkl','rb'))
book = pickle.load(open('book.pkl','rb'))
similarity_scores = pickle.load(open('similarity_scores.pkl','rb'))


main = Blueprint('main', __name__)
csrf = CSRFProtect()

@main.route('/')
def index():
    return render_template('home.html')


@main.route('/rekomendasi')
def rekomendasi_buku():
    list_popular_book = pbr_df['Book-Title'].tolist()
    books = Book.query.filter(Book.title.in_(list_popular_book)).limit(10).all()
    
    return render_template('rekomendasi_buku.html', books=books)

@main.route('/peminjaman')
def menu_peminjaman():
    return render_template('menu_peminjaman.html')

@main.route('/pengembalian')
def menu_pengembalian():
    loans = db.session.query(
        Loan.id, Student.name, Student.class_name, Book.ISBN, Book.title, Book.author, Loan.loan_date, Loan.return_date, Loan.is_return
    ).join(Student).join(Book).all()
    print(loans)
    return render_template('menu_pengembalian.html', loans=loans)

@main.route('/pengembalian/<int:id>', methods=['POST'])
def pengembalian(id):
    loan = Loan.query.get(id)
    loan.is_return = True
    db.session.commit()
    return redirect(url_for('main.menu_pengembalian'))

@main.route('/registrasi', methods=['GET', 'POST'])
def registrasi():
    if request.method == 'POST':
        name = request.form.get('name')
        class_name = request.form.get('class_name')
        address = request.form.get('address')
        fingerprint = request.form.get('fingerprint')

        if not (name and class_name and address and fingerprint):
            flash('Please fill out all fields', 'error')
        else:
            new_student = Student(name=name, class_name=class_name, address=address, fingerprint=fingerprint)
            db.session.add(new_student)
            db.session.commit()
            flash('Registrasi berhasil!', 'success')
            return redirect(url_for('main.index'))

    return render_template('registrasi.html')


@main.route('/get_students/<string:fingerprint>', methods=['GET'])
def get_students(fingerprint):
    student = Student.query.filter_by(fingerprint=fingerprint).first()
    if student:
        return {
            'message': 'success',
            'id': student.id,
            'name': student.name,
            'class_name': student.class_name,
            'address': student.address,
            'fingerprint': student.fingerprint
        }
    else:
        return {
            'message': 'failed'
        }


@main.route('/get_books/<string:ISBN>', methods=['GET'])
def get_books(ISBN):
    book = Book.query.filter_by(ISBN=ISBN).first()
    if book:
        return {
            'message': 'success',
            'id': book.id,
            'title': book.title,
            'ISBN': book.ISBN,
            'author': book.author,
            'year': book.year,
            'publisher': book.publisher,
            'image_url': book.image_url
        }
    else:
        return {
            'message': 'failed'
        }

@main.route('/loan', methods=['POST'])
def loan():
    data = request.get_json()

    fingerprint_id = data.get('fingerprint_id')
    # print(fingerprint_id)
    student = Student.query.filter_by(fingerprint=fingerprint_id).first()
    # print(student)
    student_id = student.id
    book_id = data.get('book_id')
    loan_date = data.get('loan_date')
    loan_data = datetime.strptime(loan_date, '%d-%m-%Y')
    return_date = data.get('return_date')
    return_data = datetime.strptime(return_date, '%d-%m-%Y')

    new_loan = Loan(student_id=student_id, book_id=book_id, loan_date=loan_data, return_date=return_data)
    db.session.add(new_loan)
    db.session.commit()

    return {
        'message': 'success'
    }

@main.route('/get_recommendation/<string:fingerprint_id>',methods=["GET"])
def get_recommendation(fingerprint_id):
    # print(fingerprint_id)
    try:
        student = Student.query.filter_by(fingerprint=fingerprint_id).first()
        student_id = student.id
        Loans = db.session.query(Loan.id, Student.name, Student.class_name, Book.ISBN, Book.title, Book.author, Loan.loan_date, Loan.return_date, Loan.is_return).join(Student).join(Book).filter(Loan.student_id == student_id).all()

        book_name = []
        for i in Loans:
            book_name.append(i[4])

        data_recommendation = recommendation(book_name[-1])

        book_name_recommendation = []
        for i in data_recommendation:
            book_name_recommendation.append(i[0])

        # print(book_name_recommendation)
        book_recommendation = Book.query.filter(Book.title.in_(book_name_recommendation)).limit(10).all()
    except:
        list_popular_book = pbr_df['Book-Title'].tolist()
        book_recommendation = Book.query.filter(Book.title.in_(list_popular_book)).limit(10).all()


    return render_template('rekomendasi_buku_cf.html', books=book_recommendation)


def recommendation(book_name):
    # fetching Index
    index = np.where(np.array(list(pt.index))==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[0])),reverse=True,key=lambda x:x[1])[1:9]
    
    data =[]
    for i in similar_items:
        item = []
        temp_df = book[book['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    return data

sic5-ainger-master/sic5-ainger-master/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ainger Library</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>

    <header class="text-white fs-3">
        <div class="container d-flex justify-content-between align-items-center py-3">
          <div class="d-flex align-items-center">
            <img src="{{ url_for('static', filename='images/RPL.png') }}" width="60" alt="Logo">
            <h1 class="ml-3 mb-0">Perpustakaan RPL MAALMA</h1>
          </div>
          <nav class="navbar navbar-expand-lg navbar-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" id="menu-beranda" href="{{ url_for('main.index') }}">Beranda</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="menu-rekomendasi" href="{{ url_for('main.rekomendasi_buku') }}">Rekomendasi Buku</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="menu-peminjaman" href="{{ url_for('main.menu_peminjaman') }}">Menu Peminjaman</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="menu-pengembalian" href="{{ url_for('main.menu_pengembalian') }}">Menu Pengembalian</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="menu-registrasi" href="{{ url_for('main.registrasi') }}">Registrasi</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      

{% block content %}
{% endblock %}

</body>

{% block script %}
{% endblock %}
</html>

sic5-ainger-master/sic5-ainger-master/app/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="Sambutan" style="text-align: center;">
  <br>
  <br>
  <h2>Selamat datang di</h2>
  <h2>Perpustakaan RPL MAALMA</h2>
  <p id="notif-1" >Scan sidik jarimu pada alat yang telah disiapkan</p>
  <p id="notif-2">untuk menggunakan sistem</p>
  <h3 id="notif-3" hidden>Halo <span id="notif-3-name"></span> selamat menggunakan aplikasi AINGER</h3>
  <img src="{{ url_for('static', filename='images/ARA.png') }}" width="160px">
  <img src="{{ url_for('static', filename='images/iqbal.png') }}" width="100px">

  <br>
  <button id="button-scan" type="button" class="btn btn-primary" onclick="openModal()">
    Scan
  </button>
  <button id="logout" type="button" class="btn btn-danger" onclick="logout()" hidden>
    Logout
  </button>

<!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title" id="scanning-text">Scanning</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal Body -->
            <div class="modal-body" id="modal-content">
                <span id="scan-result">Menunggu hasil scan..</span>
                <span id="user-name" hidden></span>
                <span id="user-fingerprint" hidden></span>
            </div>
            <!-- Modal Footer -->
            <div class="modal-footer">
              <button id="login-button" type="button" class="btn btn-primary" data-dismiss="modal" onclick="login()" hidden>Login</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script>

  function openModal(){
    document.getElementById("scan-result").innerText = "Menunggu Hasil Scan.."
    document.getElementById("login-button").hidden = true
    document.getElementById("user-name").innerText = ""
    document.getElementById("user-fingerprint").innerText = ""
    $('#myModal').modal('show');
  }

  function login(){
    let user_fingerprint = document.getElementById("user-fingerprint").innerText
    let user_name = document.getElementById("user-name").innerText
    sessionStorage.setItem("user_fingerprint", user_fingerprint)
    sessionStorage.setItem("user_name", user_name)
    window.location.href = "/rekomendasi"
  }

  document.getElementById("menu-beranda").classList.add("active");
  document.getElementById("menu-rekomendasi").classList.remove("active");
  document.getElementById("menu-peminjaman").classList.remove("active");
  document.getElementById("menu-pengembalian").classList.remove("active");
  // document.getElementById("menu-registrasi").classList.remove("active");

  var mqtt;
  var reconnectTimeout = 2000;
  var host="broker.hivemq.com"; //change this
  var port=8000;
  MQTTconnect();  
  function onFailure(message) {
    console.log("Connection Attempt to Host "+host+"Failed");
    setTimeout(MQTTconnect, reconnectTimeout);
      }


  function onMessageArrived(msg){
    
    if (msg.destinationName == "/sic5/ainger/sidik_jari"){
      console.log(msg.payloadString)  
      fetch("/get_students/"+msg.payloadString,{
        method: "GET"
      })
      .then(response => response.json())
      .then(data=>{
        if(data.message == "success"){
          document.getElementById("scan-result").innerText = "Selamat datang, "+data.name
          document.getElementById("user-name").innerText = data.name
          document.getElementById("user-fingerprint").innerText = data.fingerprint
          document.getElementById("login-button").hidden = false
        }
        else{
          document.getElementById("scan-result").innerText = "Data tidak ditemukan, silahkan registrasi"
        }
      })
      .catch(error => console.error('Error:', error));
    }
  }
  
  function onConnect() {
  console.log("Connected ");
  mqtt.subscribe("/sic5/ainger/#");
  }
  
  function MQTTconnect() {
  console.log("connecting to "+ host +" "+ port);
  var x=Math.floor(Math.random() * 10000); 
  var cname="orderform-"+x;
  mqtt = new Paho.MQTT.Client(host,port,cname);
  var options = {
    timeout: 3,
    onSuccess: onConnect,
    onFailure: onFailure,
    };
  mqtt.onMessageArrived = onMessageArrived
  
  mqtt.connect(options); 
  }

  document.addEventListener("DOMContentLoaded",()=>{
    let user_name = sessionStorage.getItem("user_name")
    if(user_name){
      document.getElementById("notif-1").hidden = true
      document.getElementById("notif-2").hidden = true
      document.getElementById("notif-3").hidden = false
      document.getElementById("notif-3-name").innerText = user_name
      document.getElementById("logout").hidden = false
      document.getElementById("button-scan").hidden = true
    }
  })

  function logout(){
    sessionStorage.clear()
    document.getElementById("notif-1").hidden = false
    document.getElementById("notif-2").hidden = false
    document.getElementById("notif-3").hidden = true
    document.getElementById("logout").hidden = true
    document.getElementById("button-scan").hidden = false
    window.location.reload()
  }

</script>
{% endblock %}

sic5-ainger-master/sic5-ainger-master/app/templates/menu_peminjaman.html
{% extends "base.html" %}
{% block content %}

<div id="content-loan">
<br>
<br>
<h2 style="text-align: center;">halo <span id="user-name"></span>, selamat datang di Menu Peminjaman </h2>
<br>
<div class="table-container" style="text-align: center;">
     <h3>Daftar Peminjaman Buku</h3>
     <br>
     <input type="text" id="search" placeholder="ISBN Buku">
     <br>
     <br>

     <table class="table table-striped">
        <thead>
          <tr>
            <th>No</th>
            <th>ISBN</th>
            <th>Judul Buku</th>
            <th>Publisher</th>
            <th>Author</th>
            <th>Tanggal Pinjam</th>
            <th>Tanggal Kembali</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody id="table-body">
        </tbody>

     </table>
     <span id="csrf-token" hidden>{{ csrf_token() }}</span>
    <button class="tombol-scan" style="text-align: center;" onclick="saveData()">Save</button>
<!-- tombol scan end -->
 </div>
</div>

 <div id="content-warning" hidden>
  <br>
  <br>
  <div class="container-fluid d-flex justify-content-center align-items-center">
    <h1 class="text-center">Anda Belum Login, silahkan Login</h1>
  </div>

</div>
{% endblock %}

{% block script %}
<script>
  document.getElementById("menu-beranda").classList.remove("active");
  document.getElementById("menu-rekomendasi").classList.remove("active");
  document.getElementById("menu-peminjaman").classList.add("active");
  document.getElementById("menu-pengembalian").classList.remove("active");
  // document.getElementById("menu-registrasi").classList.remove("active");

  user_name = sessionStorage.getItem("user_name")
  if(user_name==null){
    document.getElementById("content-loan").hidden = true
    document.getElementById("content-warning").hidden = false
  }
  else{
    document.getElementById("content-loan").hidden = false
    document.getElementById("content-warning").hidden = true
  }


  document.addEventListener("DOMContentLoaded",()=>{
    document.getElementById("user-name").innerText = sessionStorage.getItem("user_name")
    document.getElementById("search").addEventListener("keypress",(e)=>{
      if(e.key=="Enter"){
        search_value = document.getElementById("search").value
        console.log(search_value)
        getBookData(search_value)
      }
    })

    table_body = document.getElementById("table-body")
    books_data = JSON.parse(sessionStorage.getItem("books"))
    if(books_data!=null){
      console.log(books_data)
      books_data.forEach((element,idx) => {
      
      tr = document.createElement("tr")
      tr.innerHTML = `
        <td>${idx+1}</td>
        <td>${element.ISBN}</td>
        <td>${element.title}</td>
        <td>${element.publisher}</td>
        <td>${element.author}</td>
        <td>${element.borrow_date}</td>
        <td>${element.return_date}</td>
        <th>
          <button class="btn btn-danger" onclick="deleteItem(${idx})"> Delete </button>
        </th>
      `
      table_body.appendChild(tr)
    });
    }
    
  })

  function deleteItem(idx){
    books_data = JSON.parse(sessionStorage.getItem("books"))
    books_data.splice(idx,1)
    sessionStorage.setItem("books",JSON.stringify(books_data))
    window.location.reload()
  }

  function saveData(){
    books_data = JSON.parse(sessionStorage.getItem("books"))
    if(books_data!=null){
      books_data.forEach((element,idx) =>{
        fetch('/loan',{
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': document.getElementById("csrf-token").innerText
          },
          body: JSON.stringify({
            fingerprint_id: sessionStorage.getItem("user_fingerprint"),
            book_id: element.id,
            loan_date: element.borrow_date,
            return_date: element.return_date
          })
        })
        .then(response => response.json())
        .then(data=>{
          console.log(data)
        })
        .catch(error=>{
          console.log(error)
        })
      })
      sessionStorage.removeItem("books")
      window.location.reload()
    }
  }

  function saveBook(data){
    books_data = JSON.parse(sessionStorage.getItem("books"))
    if(books_data==null){
      books_data = []
    }
    books_data.push(data)
    sessionStorage.setItem("books",JSON.stringify(books_data))
    window.location.reload()
  }



  function getBookData(isbn){
    fetch('/get_books/'+isbn,{
      method: 'GET',
    })
    .then(response => response.json())
    .then(data=>{
      console.log(data)
      if(data.message == "success"){
        console.log(data)
        current_date = new Date()
        return_date = new Date()
        return_date.setDate(current_date.getDate()+7)
        data.borrow_date = dateFormat(current_date)
        data.return_date = dateFormat(return_date)
        saveBook(data)
      }
    })
    .catch(error=>{
      console.log(error)
    })
  }

  function dateFormat(date){
    return date.getDate()+"-"+(date.getMonth()+1)+"-"+date.getFullYear()
  }

</script>
{% endblock %}

sic5-ainger-master/sic5-ainger-master/app/templates/menu_pengembalian.html
{% extends "base.html" %}

{% block content %}
<h2 style="text-align: center;">Selamat Datang di Menu Pengembalian </h2>

<br>
<br>
<table class="table table-striped">
 <thead>
  <tr>
    <th>No.</th>
    <th>Nama Peminjam</th>
    <th>Kelas Peminjam</th>
    <th>ISBN</th>
    <th>Judul Buku</th>
    <th>Penulis</th>
    <th>Tanggal Pinjam</th>
    <th>Tanggal Kembali</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
 </thead>
 <tbody>
  {% for loan in loans %}
  <tr>
    <td>{{loop.index}}</td>
    <td>{{loan.name}}</td>
    <td>{{loan.class_name}}</td>
    <td>{{loan.ISBN}}</td>
    <td>{{loan.title}}</td>
    <td>{{loan.author}}</td>
    <td>{{loan.loan_date}}</td>
    <td>{{loan.return_date}}</td>
    <td>
      {% if loan.is_return == False %}
      <span class="badge badge-danger">Belum Kembali</span>
      {% else %}
      <span class="badge badge-success">Sudah Kembali</span>
      {% endif %}
    </td>
    <td>
      <form method="POST" action="{{ url_for('main.pengembalian', id=loan.id) }}" style="display:inline-block;">
        <input type="hidden" name="csrf_token" value = "{{ csrf_token() }}" />
        <button type="submit" class="btn btn-primary">Kembalikan</button>
    </form>
    </td>
  {% endfor %}
 </tbody>

</table>

{% endblock %}

{% block script %}
<script>
  document.getElementById("menu-beranda").classList.remove("active");
  document.getElementById("menu-rekomendasi").classList.remove("active");
  document.getElementById("menu-peminjaman").classList.remove("active");
  document.getElementById("menu-pengembalian").classList.add("active");
  // document.getElementById("menu-registrasi").classList.remove("active");
  
</script>
{% endblock %}

sic5-ainger-master/sic5-ainger-master/app/templates/registrasi.html
{% extends "base.html" %}

{% block content %}
<br>
<br>
<div class="card-form">
    <div class="form-isi">
        <h3>Registrasi</h3>
        <h4>Isikan data dengan lengkap</h4>
        <form method="POST" action="{{ url_for('main.registrasi') }}">
          <input type="hidden" name="csrf_token" value = "{{ csrf_token() }}" />  
            <fieldset>
                <input placeholder="Nama" type="text" name="name" tabindex="1" required autofocus>
            </fieldset>
            <fieldset>
                <input placeholder="Kelas" type="text" name="class_name" tabindex="2" required>
            </fieldset>
            <fieldset>
                <input placeholder="Alamat" type="text" name="address" tabindex="3" required>
            </fieldset>
            <fieldset>
                <input placeholder="Fingerprint" type="text" name="fingerprint" tabindex="4" required>
            </fieldset>
            <fieldset>
                <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Registrasi</button>
            </fieldset>
        </form>
    </div>
</div>

<br>

{% endblock %}

{% block script %}
<script>
  document.getElementById("menu-beranda").classList.remove("active");
  document.getElementById("menu-rekomendasi").classList.remove("active");
  document.getElementById("menu-peminjaman").classList.remove("active");
  // document.getElementById("menu-pengembalian").classList.remove("active");
  document.getElementById("menu-registrasi").classList.add("active");
</script>
{% endblock %}

sic5-ainger-master/sic5-ainger-master/app/templates/rekomendasi_buku.html
{% extends "base.html" %}

{% block content %}
<div id="content-recommendation">
  <br>
  <div class="rekomendasi-title">
      Buku Populer Kami
  </div>
  <!-- card book -->
  <div class="card-container">

    {% for book in books %}
    <div class="cardbaru">
      <div class="kover-buku">
        <img src="{{book.image_url}}" alt="Book Cover" class="card-image">
        <div class="detail-buku">
          <h4><b>{{book.title}}</b></h4>
          <p>{{book.author}}</p>
          <p>{{book.publisher}}</p>
          <p>{{book.year}}</p>
          <p>{{book.ISBN}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
</div>

<div class="d-flex justify-content-center">
  <a class="btn btn-primary" id="book-recommendation">Get Recommendation Book</a>
</div>
</div>

<div id="content-warning" hidden>
  <br>
  <br>
  <div class="container-fluid d-flex justify-content-center align-items-center">
    <h1 class="text-center">Anda Belum Login, silahkan Login</h1>
  </div>

</div>


<!-- card book end -->

{% endblock %}

{% block script %}
<script>
  document.getElementById("menu-beranda").classList.remove("active");
  document.getElementById("menu-rekomendasi").classList.add("active");
  document.getElementById("menu-peminjaman").classList.remove("active");
  document.getElementById("menu-pengembalian").classList.remove("active");
  // document.getElementById("menu-registrasi").classList.remove("active");
  
  user_name = sessionStorage.getItem("user_name")
  console.log(user_name)
  if(user_name==null){
    document.getElementById("content-recommendation").hidden = true
    document.getElementById("content-warning").hidden = false
  }
  else{
    document.getElementById("content-recommendation").hidden = false
    document.getElementById("content-warning").hidden = true
  }

  document.addEventListener("DOMContentLoaded",()=>{
    book_recommendation = document.getElementById("book-recommendation")
    book_recommendation.href = "/get_recommendation/"+sessionStorage.getItem("user_fingerprint")
  })

</script>
{% endblock %}

sic5-ainger-master/sic5-ainger-master/app/templates/rekomendasi_buku_cf.html
{% extends "base.html" %}

{% block content %}
<div id="content-recommendation">
  <br>
  <div class="rekomendasi-title">
      Rekomendasi buku kami untukmu
  </div>
  <!-- card book -->
  <div class="card-container">

    {% for book in books %}
    <div class="cardbaru">
      <div class="kover-buku">
        <img src="{{book.image_url}}" alt="Book Cover" class="card-image">
        <div class="detail-buku">
          <h4><b>{{book.title}}</b></h4>
          <p>{{book.author}}</p>
          <p>{{book.publisher}}</p>
          <p>{{book.year}}</p>
          <p>{{book.ISBN}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
</div>

</div>


<!-- card book end -->

{% endblock %}

{% block script %}
<script>
  document.getElementById("menu-beranda").classList.remove("active");
  document.getElementById("menu-rekomendasi").classList.add("active");
  document.getElementById("menu-peminjaman").classList.remove("active");
  document.getElementById("menu-pengembalian").classList.remove("active");
  // document.getElementById("menu-registrasi").classList.remove("active");
  
  user_name = sessionStorage.getItem("user_name")


</script>
{% endblock %}